### ISSUE TITLE
Sub0 event  - Lisbon 2023 - Booth/Demo

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdotorg#1]
# TODO

- [x] booth design
  - [tape art inspiration](https://www.pinterest.com/ninabreznik/tape-art/)
- [x] demo
  - service logs
  - slides
- [x] design
  - [moodboard](https://www.pinterest.com/serapath/datdot/)
  - [x] slides
  - [x] core diagrams in laminated prints
  - [x] banner screen saying DatDot (+ slogan?)
  - [x] invitation to discord (QR code)
- [x] follow up
  - make a selfie and make a group chat and send the selfie to remember later when we follow up

**Comment by Mehrabbruno** [comment]
### tasks - `2023.09.28`

- prepare content for lisbon event
   - design shirt
      - look for inpirtation - `15min`
      - create moodboard - `1h10min`
      - record worklog - `9min`
      - `@output` [shirts](https://www.figma.com/file/E37oG0xYYMVE90kwftT88G/datdot-event-Lisbon?type=design&node-id=18-573&mode=design&t=1ThTgL4smeTNyNc2-4)
   - slide designs
      - sketch slides - `3h4min`
      - design on figma - `5h59min`
      - update slides based on feedback - `33min`
      - update diagram 1 on figma - `47min`
      - update diagram 2 on figma - `1h33min`
      - update the prototype/animation of slides - `20min`
      - export slides (with resize canvas and color)  - `41min`
      - `@output` [slides](https://www.figma.com/file/E37oG0xYYMVE90kwftT88G/datdot-event-Lisbon?type=design&node-id=240-3844&mode=design&t=1ThTgL4smeTNyNc2-4)
   - design banner
      - look for banner inspiration
      - sketch out banner concepts - `1h13min`
      - design banner-2 - `57min`
      - design banner-1 - `43min`
         - update banner 1 - `54min`
      - update slides and banner - `2h39min`
      - `@output` [banner_v1](https://www.figma.com/file/E37oG0xYYMVE90kwftT88G/datdot-event-Lisbon?type=design&node-id=210-33392&mode=design&t=1ThTgL4smeTNyNc2-4)

---

## worklog 

[worklog-176](https://youtu.be/1sZzZr-6I9Y)

---

## feedback

---

## proposal
